---

- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: create a public zone
      route53_zone:
        zone: example.jp
        comment: this is an example zone
  tags:
    - zone


- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: create record set www.example.jp
      route53:
        state: present
        zone: example.jp
        record: www.example.jp
        type: A
        ttl: 7200
        value:
          - 192.168.1.1
          - 192.168.2.1
        wait: yes
        overwrite: yes
    - name: create record set www2.example.jp
      route53:
        state: present
        zone: example.jp
        record: www2.example.jp
        type: A
        ttl: 7200
        value:
          - 192.168.1.2
          - 192.168.2.2
        wait: yes
        overwrite: yes
  tags:
    - record
